// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.

// Generated by Quartus Prime Version 18.1.0 Build 625 09/12/2018 SJ Lite Edition
// Created on Sat May 30 03:12:35 2026

// synthesis message_off 10175

`timescale 1ns/1ns

module rx_fsm (
    reset,clock,rx_serial,bit_index_is_7,baud_tick,
    data_valid,clear_bit_index,count_en);

    input reset;
    input clock;
    input rx_serial;
    input bit_index_is_7;
    input baud_tick;
    tri0 reset;
    tri0 rx_serial;
    tri0 bit_index_is_7;
    tri0 baud_tick;
    output data_valid;
    output clear_bit_index;
    output count_en;
    reg data_valid;
    reg reg_data_valid;
    reg clear_bit_index;
    reg count_en;
    reg [3:0] fstate;
    reg [3:0] reg_fstate;
    parameter IDLE=0,START=1,DATA=2,STOP=3;

    initial
    begin
        reg_data_valid <= 1'b0;
    end

    always @(posedge clock)
    begin
        if (clock) begin
            fstate <= reg_fstate;
        end
    end

    always @(fstate or reset or rx_serial or bit_index_is_7 or baud_tick or reg_data_valid)
    begin
        if (reset) begin
            reg_fstate <= IDLE;
            reg_data_valid <= 1'b0;
            data_valid <= 1'b0;
            clear_bit_index <= 1'b0;
            count_en <= 1'b0;
        end
        else begin
            reg_data_valid <= 1'b0;
            clear_bit_index <= 1'b0;
            count_en <= 1'b0;
            data_valid <= 1'b0;
            case (fstate)
                IDLE: begin
                    if (((rx_serial == 1'b0) & (baud_tick == 1'b0)))
                        reg_fstate <= START;
                    else if (((rx_serial == 1'b1) & (baud_tick == 1'b1)))
                        reg_fstate <= IDLE;
                    // Inserting 'else' block to prevent latch inference
                    else
                        reg_fstate <= IDLE;

                    reg_data_valid <= 1'b0;
                end
                START: begin
                    if ((baud_tick == 1'b1))
                        reg_fstate <= DATA;
                    else if ((baud_tick == 1'b0))
                        reg_fstate <= START;
                    // Inserting 'else' block to prevent latch inference
                    else
                        reg_fstate <= START;

                    clear_bit_index <= 1'b1;
                end
                DATA: begin
                    if (((bit_index_is_7 == 1'b1) & (baud_tick == 1'b1)))
                        reg_fstate <= STOP;
                    else if (((bit_index_is_7 == 1'b0) & (baud_tick == 1'b0)))
                        reg_fstate <= DATA;
                    // Inserting 'else' block to prevent latch inference
                    else
                        reg_fstate <= DATA;

                    count_en <= 1'b1;
                end
                STOP: begin
                    if ((baud_tick == 1'b1))
                        reg_fstate <= IDLE;
                    else if ((baud_tick == 1'b0))
                        reg_fstate <= STOP;
                    // Inserting 'else' block to prevent latch inference
                    else
                        reg_fstate <= STOP;

                    reg_data_valid <= 1'b1;
                end
                default: begin
                    reg_data_valid <= 1'bx;
                    clear_bit_index <= 1'bx;
                    count_en <= 1'bx;
                    $display ("Reach undefined state");
                end
            endcase
            data_valid <= reg_data_valid;
        end
    end
endmodule // rx_fsm
