// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.

// Generated by Quartus Prime Version 18.1.0 Build 625 09/12/2018 SJ Lite Edition
// Created on Wed May 27 03:32:23 2026

// synthesis message_off 10175

`timescale 1ns/1ns

module tx_fsm (
    reset,clock,baud_tick,data_ready,tx_bit_7,
    tx_load_data,tx_clear_bit,tx_count_en,tx_state_idle,tx_state_start,tx_state_data,tx_state_stop);

    input reset;
    input clock;
    input baud_tick;
    input data_ready;
    input tx_bit_7;
    tri0 reset;
    tri0 baud_tick;
    tri0 data_ready;
    tri0 tx_bit_7;
    output tx_load_data;
    output tx_clear_bit;
    output tx_count_en;
    output tx_state_idle;
    output tx_state_start;
    output tx_state_data;
    output tx_state_stop;
    reg tx_load_data;
    reg tx_clear_bit;
    reg tx_count_en;
    reg tx_state_idle;
    reg tx_state_start;
    reg tx_state_data;
    reg tx_state_stop;
    reg [3:0] fstate;
    reg [3:0] reg_fstate;
    parameter START=0,DATA=1,IDLE=2,STOP=3;

    always @(posedge clock)
    begin
        if (clock) begin
            fstate <= reg_fstate;
        end
    end

    always @(fstate or reset or baud_tick or data_ready or tx_bit_7)
    begin
        if (reset) begin
            reg_fstate <= IDLE;
            tx_load_data <= 1'b0;
            tx_clear_bit <= 1'b0;
            tx_count_en <= 1'b0;
            tx_state_idle <= 1'b0;
            tx_state_start <= 1'b0;
            tx_state_data <= 1'b0;
            tx_state_stop <= 1'b0;
        end
        else begin
            tx_load_data <= 1'b0;
            tx_clear_bit <= 1'b0;
            tx_count_en <= 1'b0;
            tx_state_idle <= 1'b0;
            tx_state_start <= 1'b0;
            tx_state_data <= 1'b0;
            tx_state_stop <= 1'b0;
            case (fstate)
                START: begin
                    if (baud_tick)
                        reg_fstate <= DATA;
                    else if (~(baud_tick))
                        reg_fstate <= START;
                    // Inserting 'else' block to prevent latch inference
                    else
                        reg_fstate <= START;

                    tx_state_start <= 1'b1;

                    tx_clear_bit <= 1'b1;
                end
                DATA: begin
                    if ((baud_tick & tx_bit_7))
                        reg_fstate <= STOP;
                    else if (~((baud_tick & tx_bit_7)))
                        reg_fstate <= DATA;
                    // Inserting 'else' block to prevent latch inference
                    else
                        reg_fstate <= DATA;

                    tx_count_en <= 1'b1;

                    tx_state_data <= 1'b1;
                end
                IDLE: begin
                    if ((baud_tick & data_ready))
                        reg_fstate <= START;
                    else if (~((baud_tick & data_ready)))
                        reg_fstate <= IDLE;
                    // Inserting 'else' block to prevent latch inference
                    else
                        reg_fstate <= IDLE;

                    tx_state_idle <= 1'b1;

                    tx_load_data <= 1'b1;
                end
                STOP: begin
                    if (baud_tick)
                        reg_fstate <= IDLE;
                    else if (~(baud_tick))
                        reg_fstate <= STOP;
                    // Inserting 'else' block to prevent latch inference
                    else
                        reg_fstate <= STOP;

                    tx_state_stop <= 1'b1;
                end
                default: begin
                    tx_load_data <= 1'bx;
                    tx_clear_bit <= 1'bx;
                    tx_count_en <= 1'bx;
                    tx_state_idle <= 1'bx;
                    tx_state_start <= 1'bx;
                    tx_state_data <= 1'bx;
                    tx_state_stop <= 1'bx;
                    $display ("Reach undefined state");
                end
            endcase
        end
    end
endmodule // tx_fsm
